import type { Metadata } from "next";
import "../globals.css";
import {Navbar} from "@/srs/components/SiteComponents/Navbar";
import {Breadcrumb} from "@/srs/components/SiteComponents/Breadcrumb";
import LayoutWrapper from "@/srs/components/SiteComponents/LayoutWrapper";


export const metadata: Metadata = {
    title: "Asset Management System App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <div className="sticky top-0 z-50">
                    <Navbar/>
                </div>
                <div className="sticky top-[64px] z-40">
                    <Breadcrumb />
                </div>
                <LayoutWrapper>{children}</LayoutWrapper>
            </body>
        </html>
    )
}